marketing = ['loyality program', 'client promotion', 'market research']
print(marketing)
marketing.append('-public relations')
print(marketing)
print(marketing[3])
marketing.insert(2, 'investor relations')
print(marketing)
emailMarketing = list(marketing)
print(emailMarketing)
emailMarketing.sort()
print(emailMarketing)
internalEmails = ['internal communication']
emailMarketing.extend(internalEmails)
print(emailMarketing)
tuple = tuple(emailMarketing)
print(tuple)